![NYC Skyline](img/nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, you will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx` (Excel files).

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [78]:
# We've loaded the necessary packages for you in the first cell. Please feel free to add as many cells as you like!
suppressMessages(library(dplyr)) # This line is required to check your answer correctly
options(readr.show_types = FALSE) # This line is required to check your answer correctly
library(readr)
library(readxl)
library(stringr)

# Begin coding here ..

# Loading the data
prices <- read_csv("data/airbnb_price.csv")
room_info <- read_excel("data/airbnb_room_type.xlsx")
review <- read_tsv("data/airbnb_last_review.tsv")

# Loading necessary libraries
library(dplyr)
library(tidyverse)

# Earliest and most recent reviews:
View(review)

review <- review %>%
mutate(last_review = as.Date(last_review, format = "%B %d %Y")) 
View(review)

## first and last reviews
first_reviewed <- review %>%
summarize(first_reviewed = min(last_review))

last_reviewed <- review %>%
summarise(last_reviewed = max(last_review))
		  
# Listings of private rooms 
View(room_info)

room_info_private <- room_info %>%
mutate(room_type_revised = str_to_lower(room_type))%>%
select(-room_type) %>%
filter(room_type_revised == "private room") %>%
count(room_type_revised)

View(room_info_private)

# Extracting the counts of private room
nb_private_rooms <- room_info_private$n
nb_private_rooms

# Average listing price
View(prices)
str(prices)

## cleaning the data
prices_revised <- prices %>%
mutate(price = as.numeric(str_remove(price, " dollars"))) 

View(prices_revised)
str(prices_revised)

## average prices
avg_price <- mean(prices_revised$price)
avg_price

## rounding the average price 
avg_price <- round(avg_price , digits = 2)
avg_price


# Creating an overall tibble
review_dates <- data.frame(first_reviewed, last_reviewed, nb_private_rooms, avg_price)
head(review_dates)

Rows: 25209 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): price, nbhood_full
dbl (1): listing_id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 25209 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): host_name, last_review
dbl (1): listing_id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

      listing_id host_name        last_review
1      2595      Jennifer         May 21 2019
2      3831      LisaRoxanne      July 05 2019
3      5099      Chris            June 22 2019
4      5178      Shunichi         June 24 2019
5      5238      Ben              June 09 2019
6      5295      Lena             June 22 2019
7      5441      Kate             June 23 2019
8      5803      Laurie           June 24 2019
9      6021      Claudio          July 05 2019
10     6848      Allen & Irina    June 29 2019
11     7097      Jane             June 28 2019
12     7322      Doti             July 01 2019
13     7726      Adam And Charity June 22 2019
14     8024      Lisel            July 01 2019
15     8025      Lisel            January 01 2019
16     8110      Lisel            July 02 2019
17     8490      Nathalie         June 19 2019
18     8505      Gregory          June 23 2019
19     9518      Shon             June 15 2019
20     9657      Dana             April 19 2019
21     9668      Ssameer Or Trip  June 01 2019
22     9704      Teri             June 14 2019
23     9782      Andrea           June 15 2019
24     9783      Ssameer Or Trip  July 01 2019
25    10452      Angela           May 12 2019
26    10962      Laurie           June 21 2019
27    11708      Tyrome           June 22 2019
28    12048      Ben              July 05 2019
29    12192      Edward           June 21 2019
30    12299      Abdul            May 27 2019
⋮     ⋮          ⋮                ⋮
25180 36233091   Emily            July 03 2019
25181 36235150   Melki            July 07 2019
25182 36235154   Jason            July 03 2019
25183 36236013   Emanuel          July 05 2019
25184 36237529   Marouene         July 05 2019
25185 36238485   Ryan             July 04 2019
25186 36241283   Lana             July 02 2019
25187 36241782   Ap               July 06 2019
25188 36242888   Jean-Nicolas     July 03 2019
25189 36272851   Thikshan         July 07 2019
25190 36273046   Celine           July 06 2019
25191 36274037   Schmid           July 06 2019
25192 36280646   Chris            July 07 2019
25193 36308600   Kailey           July 05 2019
25194 36309284   Phoenix          July 04 2019
25195 36310268   Alejandro        July 06 2019
25196 36310855   Rehana           July 06 2019
25197 36318560   Linda Lou        July 06 2019
25198 36335990   Farina           July 03 2019
25199 36344079   Prince           July 04 2019
25200 36351128   David & Amy      July 05 2019
25201 36351543   Friday           July 06 2019
25202 36390226   Angela           July 08 2019
25203 36411407   Mike             July 06 2019
25204 36413632   Matt             July 07 2019
25205 36425863   Rusaa            July 07 2019
25206 36427429   H Ai             July 07 2019
25207 36438336   Ben              July 07 2019
25208 36442252   Blaine           July 07 2019
25209 36455809   Christine        July 08 2019

      listing_id host_name        last_review
1      2595      Jennifer         2019-05-21
2      3831      LisaRoxanne      2019-07-05
3      5099      Chris            2019-06-22
4      5178      Shunichi         2019-06-24
5      5238      Ben              2019-06-09
6      5295      Lena             2019-06-22
7      5441      Kate             2019-06-23
8      5803      Laurie           2019-06-24
9      6021      Claudio          2019-07-05
10     6848      Allen & Irina    2019-06-29
11     7097      Jane             2019-06-28
12     7322      Doti             2019-07-01
13     7726      Adam And Charity 2019-06-22
14     8024      Lisel            2019-07-01
15     8025      Lisel            2019-01-01
16     8110      Lisel            2019-07-02
17     8490      Nathalie         2019-06-19
18     8505      Gregory          2019-06-23
19     9518      Shon             2019-06-15
20     9657      Dana             2019-04-19
21     9668      Ssameer Or Trip  2019-06-01
22     9704      Teri             2019-06-14
23     9782      Andrea           2019-06-15
24     9783      Ssameer Or Trip  2019-07-01
25    10452      Angela           2019-05-12
26    10962      Laurie           2019-06-21
27    11708      Tyrome           2019-06-22
28    12048      Ben              2019-07-05
29    12192      Edward           2019-06-21
30    12299      Abdul            2019-05-27
⋮     ⋮          ⋮                ⋮
25180 36233091   Emily            2019-07-03
25181 36235150   Melki            2019-07-07
25182 36235154   Jason            2019-07-03
25183 36236013   Emanuel          2019-07-05
25184 36237529   Marouene         2019-07-05
25185 36238485   Ryan             2019-07-04
25186 36241283   Lana             2019-07-02
25187 36241782   Ap               2019-07-06
25188 36242888   Jean-Nicolas     2019-07-03
25189 36272851   Thikshan         2019-07-07
25190 36273046   Celine           2019-07-06
25191 36274037   Schmid           2019-07-06
25192 36280646   Chris            2019-07-07
25193 36308600   Kailey           2019-07-05
25194 36309284   Phoenix          2019-07-04
25195 36310268   Alejandro        2019-07-06
25196 36310855   Rehana           2019-07-06
25197 36318560   Linda Lou        2019-07-06
25198 36335990   Farina           2019-07-03
25199 36344079   Prince           2019-07-04
25200 36351128   David & Amy      2019-07-05
25201 36351543   Friday           2019-07-06
25202 36390226   Angela           2019-07-08
25203 36411407   Mike             2019-07-06
25204 36413632   Matt             2019-07-07
25205 36425863   Rusaa            2019-07-07
25206 36427429   H Ai             2019-07-07
25207 36438336   Ben              2019-07-07
25208 36442252   Blaine           2019-07-07
25209 36455809   Christine        2019-07-08

      listing_id description
1      2595      Skylit Midtown Castle
2      3831      Cozy Entire Floor of Brownstone
3      5099      Large Cozy 1 BR Apartment In Midtown East
4      5178      Large Furnished Room Near B'way
5      5238      Cute & Cozy Lower East Side 1 bdrm
6      5295      Beautiful 1br on Upper West Side
7      5441      Central Manhattan/near Broadway
8      5803      Lovely Room 1, Garden, Best Area, Legal rental
9      6021      Wonderful Guest Bedroom in Manhattan for SINGLES
10     6848      Only 2 stops to Manhattan studio
11     7097      Perfect for Your Parents + Garden
12     7322      Chelsea Perfect
13     7726      Hip Historic Brownstone Apartment with Backyard
14     8024      CBG CtyBGd HelpsHaiti rm#1:1-4
15     8025      CBG Helps Haiti Room#2.5
16     8110      CBG Helps Haiti Rm #2
17     8490      MAISON DES SIRENES1,bohemian apartment
18     8505      Sunny Bedroom Across Prospect Park
19     9518      SPACIOUS, LOVELY FURNISHED MANHATTAN BEDROOM
20     9657      Modern 1 BR / NYC / EAST VILLAGE
21     9668      front room/double bed
22     9704      Spacious 1 bedroom in luxe building
23     9782      Loft in Williamsburg Area w/ Roof
24     9783      back room/bunk beds
25    10452      Large B&B Style rooms
26    10962      Lovely room 2 & garden; Best area, Legal rental
27    11708      Cute apt in artist's home
28    12048      LowerEastSide apt share shortterm 1
29    12192      ENJOY Downtown NYC!
30    12299      Beautiful Sunny Park Slope Brooklyn
⋮     ⋮          ⋮
25180 36233091   1 room in bushwick
25181 36235150   Sky View beautiful apt in Williamsburg New York
25182 36235154   Top on Manhattan
25183 36236013   READY BED GO the goal is to make u feel at home
25184 36237529   Beautiful Cozy Room, 20mn to FREE ferry
25185 36238485   Chic Room in Williamsburg + Backyard +Washer Dryer
25186 36241283   Enjoy your friendly stay at my place
25187 36241782   Classic Brooklyn Loft (East Williamsburg/Bushwick)
25188 36242888   Upper East Site Luxury 2 Bed rooms
25189 36272851   Private Bedroom in a Prewar Gramercy Building!*
25190 36273046   Elegant Spacious UES private room
25191 36274037   Cozy Wall Street Studio
25192 36280646   Cable and wfi, L/G included.
25193 36308600   Cozy and Beautiful Park Slope One Bedroom
25194 36309284   Private Room Near JFK, St John's Hospital, & Beach
25195 36310268   Full size room
25196 36310855   Room 3: Cozy Room w Large Closet & Light Breakfast
25197 36318560   Luxury Sun-filled Private Room near Time Square
25198 36335990   Sunny Studio steps from Wall Street
25199 36344079   The Little Castle in Astoria
25200 36351128   One bedroom without roomies, close to everything
25201 36351543   2-MONTH SUBLEASE (WITH EARLY MOVE-IN)
25202 36390226   Comfortable clean Bedstuy private room
25203 36411407   Brand new 1 bedroom steps from Soho!
25204 36413632   Spacious 2BR in Beautiful Brooklyn Heights
25205 36425863   Lovely Privet Bedroom with Privet Restroom
25206 36427429   No.2 with queen size bed
25207 36438336   Seas The Moment
25208 36442252   1B-1B apartment near by Metro
25209 36455809   Cozy Private Room in Bushwick, Brooklyn
      room_type
1     Entire home/apt
2     Entire home/apt
3     Entire home/apt
4     private room
5     Entire home/apt
6     Entire home/apt
7     Private room
8     Private room
9     Private room
10    entire home/apt
11    Entire home/apt
12    Private room
13    Entire home/apt
14    PRIVATE ROOM
15    PRIVATE ROOM
16    Private room
17    Entire home/apt
18    Private room
19    PRIVATE ROOM
20    entire home/apt
21    PRIVATE ROOM
22    Private room
23    Private room
24    Private room
25    Private room
26    Private room
27    Entire home/apt
28    shared room
29    PRIVATE ROOM
30    Entire home/apt
⋮     ⋮
25180 Private room
25181 Entire home/apt
25182 Private room
25183 Private room
25184 Private room
25185 Private room
25186 PRIVATE ROOM
25187 PRIVATE ROOM
25188 PRIVATE ROOM
25189 Private room
25190 Private room
25191 Entire home/apt
25192 ENTIRE HOME/APT
25193 ENTIRE HOME/APT
25194 Private room
25195 Private room
25196 Private room
25197 Private room
25198 Entire home/apt
25199 private room
25200 Entire home/apt
25201 Private room
25202 PRIVATE ROOM
25203 Entire home/apt
25204 Entire home/apt
25205 PRIVATE ROOM
25206 PRIVATE ROOM
25207 Private room
25208 Entire home/apt
25209 Private room

  room_type_revised n
1 private room      11356

[1] 11356

      listing_id price       nbhood_full
1      2595      225 dollars Manhattan, Midtown
2      3831      89 dollars  Brooklyn, Clinton Hill
3      5099      200 dollars Manhattan, Murray Hill
4      5178      79 dollars  Manhattan, Hell's Kitchen
5      5238      150 dollars Manhattan, Chinatown
6      5295      135 dollars Manhattan, Upper West Side
7      5441      85 dollars  Manhattan, Hell's Kitchen
8      5803      89 dollars  Brooklyn, South Slope
9      6021      85 dollars  Manhattan, Upper West Side
10     6848      140 dollars Brooklyn, Williamsburg
11     7097      215 dollars Brooklyn, Fort Greene
12     7322      140 dollars Manhattan, Chelsea
13     7726      99 dollars  Brooklyn, Crown Heights
14     8024      130 dollars Brooklyn, Park Slope
15     8025      80 dollars  Brooklyn, Park Slope
16     8110      110 dollars Brooklyn, Park Slope
17     8490      120 dollars Brooklyn, Bedford-Stuyvesant
18     8505      60 dollars  Brooklyn, Windsor Terrace
19     9518      44 dollars  Manhattan, Inwood
20     9657      180 dollars Manhattan, East Village
21     9668      50 dollars  Manhattan, Harlem
22     9704      52 dollars  Manhattan, Harlem
23     9782      55 dollars  Brooklyn, Greenpoint
24     9783      50 dollars  Manhattan, Harlem
25    10452      70 dollars  Brooklyn, Bedford-Stuyvesant
26    10962      89 dollars  Brooklyn, South Slope
27    11708      85 dollars  Brooklyn, Bushwick
28    12048      40 dollars  Manhattan, Lower East Side
29    12192      68 dollars  Manhattan, East Village
30    12299      120 dollars Brooklyn, South Slope
⋮     ⋮          ⋮           ⋮
25180 36233091   40 dollars  Brooklyn, Bushwick
25181 36235150   170 dollars Brooklyn, Williamsburg
25182 36235154   138 dollars Manhattan, Harlem
25183 36236013   75 dollars  Brooklyn, Cypress Hills
25184 36237529   65 dollars  Staten Island, Rosebank
25185 36238485   91 dollars  Brooklyn, Williamsburg
25186 36241283   50 dollars  Brooklyn, Midwood
25187 36241782   100 dollars Brooklyn, Williamsburg
25188 36242888   220 dollars Manhattan, Upper East Side
25189 36272851   135 dollars Manhattan, Kips Bay
25190 36273046   120 dollars Manhattan, Upper East Side
25191 36274037   170 dollars Manhattan, Financial District
25192 36280646   16 dollars  Queens, Forest Hills
25193 36308600   150 dollars Brooklyn, Park Slope
25194 36309284   45 dollars  Queens, Bayswater
25195 36310268   65 dollars  Queens, Maspeth
25196 36310855   68 dollars  Brooklyn, Bedford-Stuyvesant
25197 36318560   120 dollars Manhattan, Midtown
25198 36335990   75 dollars  Manhattan, Financial District
25199 36344079   150 dollars Queens, Astoria
25200 36351128   110 dollars Manhattan, Upper West Side
25201 36351543   33 dollars  Brooklyn, Bedford-Stuyvesant
25202 36390226   45 dollars  Brooklyn, Bedford-Stuyvesant
25203 36411407   150 dollars Manhattan, Lower East Side
25204 36413632   550 dollars Brooklyn, Brooklyn Heights
25205 36425863   129 dollars Manhattan, Upper East Side
25206 36427429   45 dollars  Queens, Flushing
25207 36438336   235 dollars Staten Island, Great Kills
25208 36442252   100 dollars Bronx, Mott Haven
25209 36455809   30 dollars  Brooklyn, Bushwick

spc_tbl_ [25,209 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ listing_id : num [1:25209] 2595 3831 5099 5178 5238 ...
 $ price      : chr [1:25209] "225 dollars" "89 dollars" "200 dollars" "79 dollars" ...
 $ nbhood_full: chr [1:25209] "Manhattan, Midtown" "Brooklyn, Clinton Hill" "Manhattan, Murray Hill" "Manhattan, Hell's Kitchen" ...
 - attr(*, "spec")=
  .. cols(
  ..   listing_id = col_double(),
  ..   price = col_character(),
  ..   nbhood_full = col_character()
  .. )
 - attr(*, "problems")=<externalptr>

      listing_id price nbhood_full
1      2595      225   Manhattan, Midtown
2      3831       89   Brooklyn, Clinton Hill
3      5099      200   Manhattan, Murray Hill
4      5178       79   Manhattan, Hell's Kitchen
5      5238      150   Manhattan, Chinatown
6      5295      135   Manhattan, Upper West Side
7      5441       85   Manhattan, Hell's Kitchen
8      5803       89   Brooklyn, South Slope
9      6021       85   Manhattan, Upper West Side
10     6848      140   Brooklyn, Williamsburg
11     7097      215   Brooklyn, Fort Greene
12     7322      140   Manhattan, Chelsea
13     7726       99   Brooklyn, Crown Heights
14     8024      130   Brooklyn, Park Slope
15     8025       80   Brooklyn, Park Slope
16     8110      110   Brooklyn, Park Slope
17     8490      120   Brooklyn, Bedford-Stuyvesant
18     8505       60   Brooklyn, Windsor Terrace
19     9518       44   Manhattan, Inwood
20     9657      180   Manhattan, East Village
21     9668       50   Manhattan, Harlem
22     9704       52   Manhattan, Harlem
23     9782       55   Brooklyn, Greenpoint
24     9783       50   Manhattan, Harlem
25    10452       70   Brooklyn, Bedford-Stuyvesant
26    10962       89   Brooklyn, South Slope
27    11708       85   Brooklyn, Bushwick
28    12048       40   Manhattan, Lower East Side
29    12192       68   Manhattan, East Village
30    12299      120   Brooklyn, South Slope
⋮     ⋮          ⋮     ⋮
25180 36233091    40   Brooklyn, Bushwick
25181 36235150   170   Brooklyn, Williamsburg
25182 36235154   138   Manhattan, Harlem
25183 36236013    75   Brooklyn, Cypress Hills
25184 36237529    65   Staten Island, Rosebank
25185 36238485    91   Brooklyn, Williamsburg
25186 36241283    50   Brooklyn, Midwood
25187 36241782   100   Brooklyn, Williamsburg
25188 36242888   220   Manhattan, Upper East Side
25189 36272851   135   Manhattan, Kips Bay
25190 36273046   120   Manhattan, Upper East Side
25191 36274037   170   Manhattan, Financial District
25192 36280646    16   Queens, Forest Hills
25193 36308600   150   Brooklyn, Park Slope
25194 36309284    45   Queens, Bayswater
25195 36310268    65   Queens, Maspeth
25196 36310855    68   Brooklyn, Bedford-Stuyvesant
25197 36318560   120   Manhattan, Midtown
25198 36335990    75   Manhattan, Financial District
25199 36344079   150   Queens, Astoria
25200 36351128   110   Manhattan, Upper West Side
25201 36351543    33   Brooklyn, Bedford-Stuyvesant
25202 36390226    45   Brooklyn, Bedford-Stuyvesant
25203 36411407   150   Manhattan, Lower East Side
25204 36413632   550   Brooklyn, Brooklyn Heights
25205 36425863   129   Manhattan, Upper East Side
25206 36427429    45   Queens, Flushing
25207 36438336   235   Staten Island, Great Kills
25208 36442252   100   Bronx, Mott Haven
25209 36455809    30   Brooklyn, Bushwick

tibble [25,209 × 3] (S3: tbl_df/tbl/data.frame)
 $ listing_id : num [1:25209] 2595 3831 5099 5178 5238 ...
 $ price      : num [1:25209] 225 89 200 79 150 135 85 89 85 140 ...
 $ nbhood_full: chr [1:25209] "Manhattan, Midtown" "Brooklyn, Clinton Hill" "Manhattan, Murray Hill" "Manhattan, Hell's Kitchen" ...

[1] 141.7779

[1] 141.78

  first_reviewed last_reviewed nb_private_rooms avg_price
1 2019-01-01     2019-07-09    11356            141.78